# Generated by Django 5.1.2 on 2025-04-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NonExistentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='bg_color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(blank=True, max_length=14888),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_viewer.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_viewer.pdfdocument'),
        ),
        migrations.AddField(
            model_name='comment',
            name='start_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.user'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='name',
            field=models.CharField(max_length=228, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_viewer.issue'),
        ),
    ]
