# Generated by Django 5.1.2 on 2025-08-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0002_issue_nonexistentuser_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='issue',
        ),
    ]
