# Generated by Django 5.1.2 on 2025-08-28 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0003_remove_pdfdocument_author_remove_pdfdocument_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='start_index',
        ),
        migrations.AddField(
            model_name='comment',
            name='position',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdf_viewer.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdf_viewer.user'),
        ),
    ]
