# Generated by Django 5.1.2 on 2025-08-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0004_user_remove_comment_start_index_comment_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='is_annotated',
            field=models.BooleanField(default=False),
        ),
    ]
