# Generated by Django 5.1.2 on 2025-08-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0005_pdfdocument_is_annotated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdf_viewer.user'),
        ),
    ]
