# Generated by Django 5.1.2 on 2025-09-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0006_alter_pdfdocument_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_com',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pdf',
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdf_viewer.user')),
                ('pdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_viewer.pdfdocument')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_annot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_viewer.annotation'),
        ),
    ]
