# Generated by Django 5.1.2 on 2025-09-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0007_rename_parent_comment_parent_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pdf_viewer.user'),
        ),
    ]
