# Generated by Django 5.1.2 on 2025-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0008_alter_annotation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='pymupdf_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
