# Generated by Django 5.1.2 on 2025-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0009_annotation_pymupdf_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='pymupdf_id',
        ),
        migrations.AddField(
            model_name='annotation',
            name='xref',
            field=models.IntegerField(null=True),
        ),
    ]
