# Generated by Django 5.1.2 on 2025-10-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0010_remove_annotation_pymupdf_id_annotation_xref'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annot_color',
            field=models.CharField(default='#ffff00', max_length=7),
        ),
    ]
