# Generated by Django 5.1.2 on 2025-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_viewer', '0011_user_annot_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='annot_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
